# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bands_cpp <- function(mbeta, mbeta2, Bs, beta, alpha) {
    .Call('_HFM_bands_cpp', PACKAGE = 'HFM', mbeta, mbeta2, Bs, beta, alpha)
}

NBmix_mcmc <- function(y, X, Bs, burnin, nsim, thin, spatial = TRUE) {
    .Call('_HFM_NBmix_mcmc', PACKAGE = 'HFM', y, X, Bs, burnin, nsim, thin, spatial)
}

NSmix_mcmc <- function(y, X, Bs, nfac, burnin, nsim, thin) {
    .Call('_HFM_NSmix_mcmc', PACKAGE = 'HFM', y, X, Bs, nfac, burnin, nsim, thin)
}

SSmix_mcmc <- function(y, X, Bs, nfacL, nfacR, burnin, nsim, thin) {
    .Call('_HFM_SSmix_mcmc', PACKAGE = 'HFM', y, X, Bs, nfacL, nfacR, burnin, nsim, thin)
}

